"""
layout.py — render the city's streets, zones, and buildings as JSON.

Why
---
The M1 city generator already builds a road network + zoning map, but
the API didn't expose them.  The M5 visualiser needs:

  - roads: list of (u, v) line segments with their kind (street / avenue).
  - zones: per-block assignment ("residential" | "industrial" |
           "commercial" | "critical").
  - buildings: per-node summary (id, type, x, y, label, priority).

This module is a pure read-only view over the grid and the
``RoadNetwork`` + ``Zoning`` references we already stash on the grid
during generation.  It never mutates the grid.

Backward compatibility
----------------------
The new endpoint ``/city/layout`` sits next to the existing
``/city/profile`` and ``/city/report``; nothing existing is modified.
"""

from __future__ import annotations

from typing import Any, Dict, List


def _zone_polygons(road_zones: Dict[Any, str]) -> List[Dict[str, Any]]:
    """Return a list of zone polygons (one per contiguous block).

    Each polygon is a small square cell with the uniform centre of
    the roads in that zone.  This is a *visualisation* helper — the
    exact polygons are not mathematically critical, but their visual
    placement should match the road network.
    """
    by_zone: Dict[str, List[Any]] = {}
    for block, zone in road_zones.items():
        by_zone.setdefault(zone, []).append(block)
    out: List[Dict[str, Any]] = []
    for zone, blocks in by_zone.items():
        if not blocks:
            continue
        xs = [p[0] for p in blocks]
        ys = [p[1] for p in blocks]
        cx = sum(xs) / len(xs)
        cy = sum(ys) / len(ys)
        # Use the bounding box ± block_size as a rough polygon.
        width = (max(xs) - min(xs)) + 80.0
        height = (max(ys) - min(ys)) + 80.0
        min_x = min(xs) - 40.0
        min_y = min(ys) - 40.0
        out.append({
            "zone": zone,
            "centroid": [cx, cy],
            "polygon": [
                [min_x, min_y],
                [min_x + width, min_y],
                [min_x + width, min_y + height],
                [min_x, min_y + height],
            ],
            "block_count": len(blocks),
        })
    return out


def buildings(grid: Any) -> List[Dict[str, Any]]:
    """Return a serialisable list of every node."""
    out: List[Dict[str, Any]] = []
    for nid, node in grid.nodes.items():
        out.append({
            "id": nid,
            "node_type": getattr(node, "node_type", "generic"),
            "label": getattr(node, "label", nid),
            "x": float(getattr(node, "x", 0.0)),
            "y": float(getattr(node, "y", 0.0)),
            "priority": int(getattr(node, "priority", 3)),
            "street": getattr(node, "street", ""),
            "role": getattr(node, "role", "load"),
        })
    return out


def city_layout(grid: Any) -> Dict[str, Any]:
    """Render the city as a JSON-friendly dict.

    Returns ``{}`` if the grid was not generated by ``CityGenerator``
    (legacy grid, no road network) so the endpoint stays backward
    compatible.
    """
    road = getattr(grid, "_road_network", None)
    zoning = getattr(grid, "_zoning", None)
    if road is None or zoning is None:
        return {"has_layout": False}
    bounds = road.bounds
    roads: List[Dict[str, Any]] = []
    for u, v, data in road.graph.edges(data=True):
        roads.append({
            "u": [float(u[0]), float(u[1])],
            "v": [float(v[0]), float(v[1])],
            "kind": data.get("kind", "street"),
            "length": float(data.get("length", 0.0)),
        })
    zones = _zone_polygons(zoning.zones)
    return {
        "has_layout": True,
        "bounds": {
            "min_x": float(bounds[0]),
            "min_y": float(bounds[1]),
            "max_x": float(bounds[2]),
            "max_y": float(bounds[3]),
        },
        "roads": roads,
        "zones": zones,
        "buildings": buildings(grid),
    }
